// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


console.log("ReasonReact".includes("Reason"));

console.log("Reason".includes("ReasonReact"));

console.log("ReasonReact".includes("Reason"));

var BetterString = /* module */[];

console.log("ReasonReact".includes("Reason"));

exports.BetterString = BetterString;
/*  Not a pure module */
