// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Belt_Map = require("bs-platform/lib/js/belt_Map.js");
var Caml_primitive = require("bs-platform/lib/js/caml_primitive.js");

function cmp(a, b) {
  var x = Caml_primitive.caml_string_compare(a[/* title */0], b[/* title */0]);
  if (x !== 0) {
    return x;
  } else {
    return Caml_primitive.caml_string_compare(a[/* author */1], b[/* author */1]);
  }
}

var BookCompare = Belt_Id.MakeComparable(/* module */[/* cmp */cmp]);

var reviews = Belt_Map.make(BookCompare);

var book = /* record */[
  /* title */"Incarnadine",
  /* author */"Szybist, Mary"
];

var review = /* record */[
  /* name */"John",
  /* date */1568898720165.0,
  /* text */"Great collection! I liked the poem *Invitation*.",
  /* rating : Five */4
];

var reviews$1 = Belt_Map.set(reviews, book, /* :: */[
      review,
      /* [] */0
    ]);

console.log("reviews", reviews$1);

exports.BookCompare = BookCompare;
exports.book = book;
exports.review = review;
exports.reviews = reviews$1;
/* BookCompare Not a pure module */
