// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");

var apples = Js_dict.fromArray(/* array */[/* tuple */[
        "taste",
        "sweet"
      ]]);

console.log("apples", apples);

function eatFruits(fruit) {
  console.log("Eating fruits", fruit);
  return /* () */0;
}

console.log("Eating fruits", apples);

exports.apples = apples;
exports.eatFruits = eatFruits;
/* apples Not a pure module */
